[platformio]
default_envs = sender

[env]
platform = espressif32 @ 6.4.0
framework = arduino
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
	-DCORE_DEBUG_LEVEL=5
	-DARDUINO_USB_MODE=1
lib_deps = 
    m5stack/M5Unified@^0.1.16
    m5stack/M5-SX127x@^1.0.0

[env:sender]
board = m5stack-core-esp32
build_flags = 
    -DSENDER
    ${env.build_flags}
lib_deps = 
    ${env.lib_deps}
    tinyu-zhao/TinyGPSPlus-ESP32@^0.0.2
upload_port  = /dev/cu.usbserial-5AE20095001
monitor_port = /dev/cu.usbserial-5AE20095001

[env:receiver]
board = m5stack-core-esp32
build_flags = 
    -DRECEIVER
    ${env.build_flags}
lib_deps = 
    ${env.lib_deps}

upload_port  = /dev/cu.usbserial-58FE0074911
monitor_port = /dev/cu.usbserial-58FE0074911