[platformio]
default_envs = sender

[env]
platform = espressif32
framework = arduino
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
	-DCORE_DEBUG_LEVEL=3
	-DARDUINO_USB_MODE=1
    -O3
lib_deps = 
    m5stack/M5Unified
    m5stack/M5GFX
    m5stack/M5-SX127x
    knolleary/PubSubClient
    bblanchon/ArduinoJson

[env:sender]
board = m5stack-cores3
build_flags = 
    -DCORE2
    -DSENDER 
    ;-DENV3
    ${env.build_flags}
lib_deps = 
    ${env.lib_deps}
    tinyu-zhao/TinyGPSPlus-ESP32
    m5stack/M5UnitUnified
    m5stack/M5Unit-ENV
	m5stack/M5Unit-TOF@^0.2.0
upload_protocol = espota
upload_port = 192.168.1.12
monitor_port = /dev/cu.usbmodem12201
;upload_port = ${env:sender.monitor_port}

[env:sender-M5Basic]
board = m5stack-core-esp32
upload_protocol = espota
upload_port = 192.168.1.28
monitor_port = /dev/cu.usbserial-5AE20095001
;upload_port = /dev/cu.usbserial-5AE20095001
build_flags = 
    -DARDUINO_M5STACK_BASIC
    -DSENDER
    ${env:sender.build_flags}
lib_deps = 
    ${env:sender.lib_deps}

[env:receiver]
;board = m5stack-core-esp32
board = m5stack-cores3
build_flags = 
    -DCORE3
    -DRECEIVER
    -DARDUINO_M5STACK_CORES3
    ${env.build_flags}
lib_deps = 
    ${env.lib_deps}

;upload_protocol = espota
;upload_port = 192.168.1.20
monitor_port = /dev/cu.usbmodem2101
upload_port = ${env:receiver.monitor_port}
