[platformio]
default_envs = sender

[env]
platform = espressif32
framework = arduino
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
	-DCORE_DEBUG_LEVEL=3
	-DARDUINO_USB_MODE=1
lib_deps = 
    m5stack/M5Unified
    m5stack/M5GFX
    m5stack/M5-SX127x
    knolleary/PubSubClient
    bblanchon/ArduinoJson

[env:sender]
board = m5stack-cores3
build_flags = 
    -DSENDER
    ${env.build_flags}
lib_deps = 
    ${env.lib_deps}
    tinyu-zhao/TinyGPSPlus-ESP32
upload_protocol = espota
upload_port = 192.168.1.12
monitor_port = /dev/cu.usbmodem1301
;upload_port = ${env:sender.monitor_port}

[env:receiver]
;board = m5stack-core-esp32
board = m5stack-cores3
build_flags = 
    -DRECEIVER
    -DARDUINO_M5STACK_BASIC
    ${env.build_flags}
lib_deps = 
    ${env.lib_deps}

;upload_protocol = espota
;upload_port = 192.168.1.20
monitor_port = /dev/cu.usbmodem2101
upload_port = ${env:receiver.monitor_port}
